package com.example.Pastach.dto.user;

import lombok.Getter;
import lombok.Setter;

import java.time.LocalDate;

@Getter
@Setter
public class UserCreateDTO {
    private String id; // not autogenerated!
    private String userName;
    private String email;
    private LocalDate birthday;
}
