# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: recposts.proto
# Protobuf Python Version: 4.25.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0erecposts.proto\x12\x06recsys\"Y\n\x19GetRecommendationsRequest\x12\x0f\n\x07user_id\x18\x01 \x01(\x03\x12\r\n\x05limit\x18\x02 \x01(\x05\x12\x1c\n\x14\x65xclude_author_posts\x18\x03 \x01(\x08\"<\n\x0fRecommendedPost\x12\x0f\n\x07post_id\x18\x01 \x01(\x03\x12\x18\n\x10similarity_score\x18\x02 \x01(\x01\"t\n\x1aGetRecommendationsResponse\x12\x0f\n\x07user_id\x18\x01 \x01(\x03\x12\x30\n\x0frecommendations\x18\x02 \x03(\x0b\x32\x17.recsys.RecommendedPost\x12\x13\n\x0btotal_count\x18\x03 \x01(\x05\x32v\n\x15RecommendationService\x12]\n\x12GetRecommendations\x12!.recsys.GetRecommendationsRequest\x1a\".recsys.GetRecommendationsResponse\"\x00\x42\x34\n!com.example.Pastach.grpc.recpostsB\rRecPostsProtoP\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'recposts_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  _globals['DESCRIPTOR']._options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n!com.example.Pastach.grpc.recpostsB\rRecPostsProtoP\001'
  _globals['_GETRECOMMENDATIONSREQUEST']._serialized_start=26
  _globals['_GETRECOMMENDATIONSREQUEST']._serialized_end=115
  _globals['_RECOMMENDEDPOST']._serialized_start=117
  _globals['_RECOMMENDEDPOST']._serialized_end=177
  _globals['_GETRECOMMENDATIONSRESPONSE']._serialized_start=179
  _globals['_GETRECOMMENDATIONSRESPONSE']._serialized_end=295
  _globals['_RECOMMENDATIONSERVICE']._serialized_start=297
  _globals['_RECOMMENDATIONSERVICE']._serialized_end=415
# @@protoc_insertion_point(module_scope)
