ALTER TABLE public.posts
    ADD COLUMN IF NOT EXISTS comments_count BIGINT NOT NULL DEFAULT 0,
    ADD COLUMN IF NOT EXISTS likes_count    BIGINT NOT NULL DEFAULT 0,
    ADD COLUMN IF NOT EXISTS dislikes_count BIGINT NOT NULL DEFAULT 0;

ALTER TABLE public.comments
    ADD COLUMN IF NOT EXISTS likes_count    BIGINT NOT NULL DEFAULT 0,
    ADD COLUMN IF NOT EXISTS dislikes_count BIGINT NOT NULL DEFAULT 0;